### PR TITLE
--author-date-order

### PR DESCRIPTION
**Pull request by faisal-shah**
Add support for --author-date-order.

### CODE REVIEW

**Comment by rbong** [comment]
The biggest general problem with this change is that there's more kinds of sorting than `--author-date-order`. It isn't any more "sorted" than the default reverse chronological order, or other kinds of sorting like topographical order. It's just using a different value to sort commits.

The fact that it's not any more sorted makes displaying `[sorted]` inaccurate when it's enabled, and it makes other references to the idea that this option sorts the commits as if they won't otherwise be sorted similarly inaccurate. Having an option to "trigger" sorting also does not take into account that there are other sorting methods that may also be desirable. I would like to not have a sorting feature change a lot once it's implemented.

It also doesn't take into account conflicts with existing options - I know the reflog option is one, I'm not sure there are others. It should probably be ignored in this case.

I'm not sure there's a great interface here to implement sorting in general that covers all of the bases, but I'm open to suggestions.

**Comment by faisal-shah** [comment]
I agree with you. It's too opinionated to be put in the plugin ..

**Comment by faisal-shah** [comment]
How about cycling between the 4 sort options:

--date-order
--author-date-order
--topo-order
--reverse


?

**Comment by rbong** [comment]
I've been thinking about how I'd like sorting to be implemented. I don't use sorting myself, but it seems like it should be useful for some people. I didn't want to make you reimplement this MR so I went ahead and implemented it myself.

You can now use `-sort=<date,author,topo>` to set the sort type. You can also use the `-reverse` boolean option to reverse sorting.

As far as keybindings go, you can use `gss` to cycle through the three different types. You can use `gsd`, `gsa`, and `gst` to set date/author/topo sorting respectively. You can use `gsr` to toggle reversing.

The reason that this is a little different than how `git log` implements it is because we don't support ordered options. I think that the behavior might slightly change for `git log` if you pass in 2 or more different options in different orders (but I didn't experiment too much). A lot of things would have to change to implement ordered options, so I hope this interface is okay for now. I think it's a little bit simpler than the way `git log` does it too, with the downside that there's more to remember if you're already used to `git log`, but that's already true for different options because of how vim argument parsing just works differently.

If you do want to customize how sorting works, change the `g:flog_sort_types` argument. This is undocumented for now but it looks like this:

```vim
let g:flog_sort_types = [
      \ { 'name': 'date', 'args': '--date-order' },
      \ { 'name': 'author', 'args': '--author-date-order' },
      \ { 'name': 'topo', 'args': '--topo-order' },
      \ ]
```

Using this variable, you can change the cycle order, enabled sorting types, and add composite types or change the default types if you want.

I wasn't able to find any conflicting options for sorting. I could have sworn there were some. Oh well.

Again I don't use sorting much myself, so feedback is welcome. Also let me know if there are any problems.

**Comment by faisal-shah** [comment]
Awesome, thanks for taking time to address this! I like how you implemented this feature.

I'm working on a project with many branches being actively developed. Several branches modify core library files - without pushing their changes to the 'master' branch. Yech, nasty stuff. So, I like viewing all branches in a certain path (say, common library stuff), and sorting by author-date to see the latest changes made to files in that path by all the branches.

**Pull request closed without merging**
