### PR TITLE
'Custom config' explanation in README from #38

### PR DESCRIPTION
**Pull request by TamaMcGlinn**
Took your explanation from #38 together with a selection of my own documented bindings and put them in the readme. You can view the end result on my fork; I've checked all the links work.

### CODE REVIEW

**Comment by rbong** [comment]
Thanks for the MR. I recently made an attempt to improve documentation as well. Here are the changes I made:

- [README](https://github.com/rbong/vim-flog)
- [Examples](https://github.com/rbong/vim-flog/blob/master/EXAMPLES.md)

Let me know if you think I still need to add anything else.

**Comment by TamaMcGlinn** [comment]
Your 'improve documentation' commit certainly improves things, but:
- the statement regarding exposing helper functions rather than configuration options is a global design decision and I think you should state that in the README.
- I added a lot more example configurations, which I think is useful, although I agree it is probably better to put those into the examples file instead.
- Your example `D` mapping diffs the counterintuitive way. Visual mode uses `'<` for the top line and `'>` for the lower line (vim doesn't care if you started at the top or at the bottom). But since the top commit in the graph is the most recent, the more logical mapping is the one I gave in my example - and yet sometimes you want the opposite, so I mapped `DD` to that. This is one of the details in the example I gave which I think is helpful when people are making their own mappings.

So I would still recommend merging this; and then perhaps move my example bindings into Examples (replacing `D`).

**Comment by rbong** [comment]
>the statement regarding exposing helper functions rather than configuration options is a global design decision and I think you should state that in the README.

Good point. I think this idea can be intimidating at first but it is important and I don't see a way around it without being too obtuse. I've added it to the README.
>I added a lot more example configurations, which I think is useful, although I agree it is probably better to put those into the examples file instead.

I agree that more examples are useful, but also I like to keep documentation short for easier maintenance and readability.

I've created the [Custom Commands](https://github.com/rbong/vim-flog/wiki/Custom-Commands) page on the wiki for adding more examples. I've linked this in the main documentation and opened up the Wiki to everyone. I've also tried to incorporate some of the new ideas you've presented in your examples into the main documentation in brief.
>Your example D mapping diffs the counterintuitive way. Visual mode uses '< for the top line and '> for the lower line (vim doesn't care if you started at the top or at the bottom). But since the top commit in the graph is the most recent, the more logical mapping is the one I gave in my example - and yet sometimes you want the opposite, so I mapped DD to that. This is one of the details in the example I gave which I think is helpful when people are making their own mappings.

Also a good point. I thought the fact that I was re-implementing a command while using a different binding was confusing in my example. This is a nice little change that I can easily see how some people would prefer. I've now changed the example to switch the order of `dd`. I hope it's still clear that users can add their own bindings, but I also hope it's clearer now that they can overwrite existing bindings.

Let me know what you think.

**Comment by TamaMcGlinn** [comment]
Ah, great work documenting my bindings. I had forgotten that I was overriding `cm`. You've covered everything in my pullrequest now, and I see the links README > Examples > Wiki allow readers to access more and more detail. Looks good to me!

**Pull request closed without merging**
